linters:
  enable-all: true
  disable:
    - depguard
    - exhaustivestruct
    - godox
    - exhaustruct
    - lll
linters-settings:
  tagliatelle:
    case:
      rules:
        env: upperSnake
run:
  timeout: 1m
