// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.6
// source: jwt/jwt.proto

package jwt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JWTClaims struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // UUID
	AccessLevel int32  `protobuf:"varint,2,opt,name=access_level,json=accessLevel,proto3" json:"access_level,omitempty"`
}

func (x *JWTClaims) Reset() {
	*x = JWTClaims{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jwt_jwt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JWTClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTClaims) ProtoMessage() {}

func (x *JWTClaims) ProtoReflect() protoreflect.Message {
	mi := &file_jwt_jwt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTClaims.ProtoReflect.Descriptor instead.
func (*JWTClaims) Descriptor() ([]byte, []int) {
	return file_jwt_jwt_proto_rawDescGZIP(), []int{0}
}

func (x *JWTClaims) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JWTClaims) GetAccessLevel() int32 {
	if x != nil {
		return x.AccessLevel
	}
	return 0
}

var File_jwt_jwt_proto protoreflect.FileDescriptor

var file_jwt_jwt_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6a, 0x77, 0x74, 0x2f, 0x6a, 0x77, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x6a, 0x77, 0x74, 0x22, 0x47, 0x0a, 0x09, 0x4a, 0x57, 0x54, 0x43, 0x6c, 0x61, 0x69, 0x6d,
	0x73, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x42, 0x27, 0x5a,
	0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4f, 0x73, 0x69, 0x70,
	0x79, 0x61, 0x6e, 0x47, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x6a, 0x77, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jwt_jwt_proto_rawDescOnce sync.Once
	file_jwt_jwt_proto_rawDescData = file_jwt_jwt_proto_rawDesc
)

func file_jwt_jwt_proto_rawDescGZIP() []byte {
	file_jwt_jwt_proto_rawDescOnce.Do(func() {
		file_jwt_jwt_proto_rawDescData = protoimpl.X.CompressGZIP(file_jwt_jwt_proto_rawDescData)
	})
	return file_jwt_jwt_proto_rawDescData
}

var file_jwt_jwt_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_jwt_jwt_proto_goTypes = []any{
	(*JWTClaims)(nil), // 0: jwt.JWTClaims
}
var file_jwt_jwt_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jwt_jwt_proto_init() }
func file_jwt_jwt_proto_init() {
	if File_jwt_jwt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jwt_jwt_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*JWTClaims); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jwt_jwt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jwt_jwt_proto_goTypes,
		DependencyIndexes: file_jwt_jwt_proto_depIdxs,
		MessageInfos:      file_jwt_jwt_proto_msgTypes,
	}.Build()
	File_jwt_jwt_proto = out.File
	file_jwt_jwt_proto_rawDesc = nil
	file_jwt_jwt_proto_goTypes = nil
	file_jwt_jwt_proto_depIdxs = nil
}
